config/routes.rb
Rails.application.routes.draw do
  namespace :buyers do
    get 'buyer/show_products'
    post 'buyer/add_to_cart'
    get 'buyer/show_cart'
  end
  # get "cart/add_to_cart"
  resources :stores
  devise_for :buyers, path: "buyers", controllers: {
                        registerations: "buyers/registrations",
                        sessions: "buyers/sessions",
                        confirmation: "buyers/confirmations",
                        passwords: "buyers/passwords",
                      }
  devise_for :sellers, controllers: {
                         #   registrations: 'sellers/registrations',
                         sessions: "sellers/sessions",
                         confirmation: "sellers/confirmations",
                         passwords: "sellers/passwords",
                         registerations: "sellers/registrations",
                       }

  get "welcome/index"
  devise_for :users, path: "users", controllers: {
                       registerations: "users/registrations",
                       sessions: "users/sessions",
                       confirmation: "users/confirmations",
                       passwords: "users/passwords",
                     }
  resources :categories
  resources :brands
  resources :products
  root "products#index"
  resources :seller_objects
  resources :searches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  post "authenticate", to: "authentication#authenticate"

  get 'order/confirm', to: 'order#confirm'
  get 'order/deliver', to: 'order#deliver'
  get 'order/showpending' , to: 'order#show_pending'
  put 'order/update_status/:id' , to: 'order#update_status' 
  resources :order

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       case user
       when User
        can :read, Product
        can :create, Seller
       when Seller
        can :manage, Product
       when Buyer
        can :read, Product
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/api_user.rb
class ApiUser < ApplicationRecord
    has_secure_password
end

app/models/apiuser.rb
class Apiuser< ApplicationRecord
    has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :product
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

  has_and_belongs_to_many :products
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product
end

app/models/order.rb
class Order < ApplicationRecord
    has_and_belongs_to_many :products
end
  

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    has_and_belongs_to_many :stores
    has_and_belongs_to_many :buyers
    has_and_belongs_to_many :orders
    belongs_to :brand
    belongs_to :category
    validates :title, :description, :price, :in_stock_quantity ,:image , presence: true
    def self.search(search)
        if search
            where(["title like ? ","%#{search}%"])
        else
            all
        end
    end 
end

app/models/search.rb
class Search < ApplicationRecord
    def products
        @products ||= find_products
    end
    private
    def find_products
        products = Product.order(:title)
        products = products.where("title LIKE ?" , "%#{title}%") if title.present?
        products = products.where(category_id: category_id) if category_id.present?
        products = products.where(brand_id: brand_id) if brand_id.present?
        products = products.where(store_id: store_id) if store_id.present?
        products = products.where("price >= ?" , min_price) if min_price.present?
        products = products.where("price <= ?" , max_price) if max_price.present?
        return products
    end
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :sellers
    has_and_belongs_to_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def new 
        @search = Search.new
    end

    def create
        @search = Search.create!(search_params)
        redirect_to @search
    end

    def show
        @search = Search.find(params[:id])
    end
    private
    def search_params
        params.require(:search).permit(:title, :description, :brand_id, :category_id, :store_id , :min_price , :max_price )
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/searches/new.html.erb
<h1> Advanced Search </h1>
<p> <%= link_to 'Back' , products_path %> </p>
<%= form_for @search do |f| %>
    <div class="field">
        <%= f.label :title%>
        <%= f.text_field :title %>
    </div>
    <div class="field">
         <%= f.label :description%>
        <%= f.text_area :description %>
    </div>
    <div class="field">
        <%= f.label :category_id%> <br/>
        <%= f.collection_select :category_id , Category.order(:name) , :id , :name , include_blank: true%>
    </div>
    <div class="field">
        <%= f.label :brand_id%> <br/>
        <%= f.collection_select :brand_id , Brand.order(:name) , :id , :name , include_blank: true%>
    </div>
    <div class="field">
        <%= f.label :store_id%> <br/>
        <%= f.collection_select :store_id , Store.order(:name) , :id , :name , include_blank: true%>
    </div>
    <div class="field">
        <%= f.label :min_price , "Price Range"%><br/>
        <%= f.text_field :min_price , size: 10 %>
        <%= f.text_field :max_price , size: 10%>
    </div>
    <div class="action" ><%= f.submit "Search"%> </div>
<% end %>

app/views/searches/show.html.erb
<h1>Search Result </h1>
<p> <%= link_to 'Back' , new_search_path %> </p>
    <% if @search.products.empty? %>
        <p> No Products Found </p>
    <% else %>
        <% @search.products.each do |c| %>
            <br>
            <div class= "div">
                <h1><%= c.title %> </h1>
                <p> Price: <%= c.price%> L.E </p>
                <p> Category: <%= c.category.name%> </p>
                <p> Brand: <%= c.brand.name%> </p>
                <p> Description: <%= c.description%> </p>
            </div>
        <% end %>
    <% end %>